In [6]:
import pandas as pd

In [7]:
# Given the Positions DD.MM.YY.xlsx file => 
# To right end of table:
# Column title: Ticker. Row under: =C5.[Ticker symbol] and drag down
# Column title: Exchange. Row under: =C5.[Exchange abbreviation] and drag down

df = pd.read_excel("Positions 19.11.22.xlsx") # Base csv
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Company Information,NaN,NaN,Shareprice,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Measures,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Sector,Company,Buying Date,Share Price,Target Price,Deviation from\n Target Price,Currency,Current in €,Last Meeting,...,Total Return per Industry,Market Cap,Market Cap in € (B),P/E ratio,Weight in Portofolio,Weight Industry,Optimization Weight (Risk Team),Ticker,Exchange,NaN
3,NaN,Consumer Goods,NaN,2020-10-16 00:00:00,27.595,30.21,-0.086561,EUR,27.595,27.75,...,-0.003256,28856780000,28.85678,11.6653,0.020562,0.098705,0.025,AD,XAMS,NaN
4,NaN,NaN,NaN,2021-06-06 00:00:00,540.4,765,-0.293595,EUR,540.4,543.6,...,NaN,68774950000,68.77495,18.1789,0.040268,NaN,0.025,KER,XPAR,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NaN,NaN,NaN,Share Price,11.258489,NaN,SEK,NaN,10.9754,10.7327,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,CAD,NaN,1.3818,1.3721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,NaN,NaN,NaN,NaN,DKK,NaN,7.4373,7.4357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,NaN,NaN,NaN,NaN,HKD,NaN,8.0748,8.1117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,NaN,NaN,Adjust when buying Tech.,NaN,Cash,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def process(data):
    temp = data.copy()
    temp.columns = temp.iloc[2] # Set column names
    endIdx = temp.index[temp['Sector'] == "CASH"].tolist()[0] # Last row of table (Own discretion)

    temp = temp.iloc[3:endIdx-1] # Only keep rows from table
    temp = temp.dropna(how='all').iloc[: , 1:].reset_index(drop=True) # Drop all empty rows + first column
    temp['Optimization Weight (Risk Team)'] = temp['Optimization Weight (Risk Team)'].fillna(-1)
    temp = temp.ffill() # Propagate values down to NaNs (for Sector and Industry columns)
    temp = temp.drop(columns="Company")
    temp = temp.dropna(how="all", axis=1)
    return temp

data = process(df)
data

2,Sector,Buying Date,Share Price,Target Price,Deviation from\n Target Price,Currency,Current in €,Last Meeting,Initial,Shares,...,Weekly Return per Industry,Total Return per Industry,Market Cap,Market Cap in € (B),P/E ratio,Weight in Portofolio,Weight Industry,Optimization Weight (Risk Team),Ticker,Exchange
0,Consumer Goods,2020-10-16,27.5950,30.21,-0.086561,EUR,27.595000,27.750000,25.340000,40,...,0.000134,-0.003256,28856780000,28.856780,11.6653,0.020562,0.098705,0.0250,AD,XAMS
1,Consumer Goods,2021-06-06,540.4000,765.00,-0.293595,EUR,540.400000,543.600000,600.100000,4,...,0.000134,-0.003256,68774950000,68.774950,18.1789,0.040268,0.098705,0.0250,KER,XPAR
2,Consumer Goods,2022-03-08,208.4000,259.52,-0.196979,USD,201.859744,197.372488,209.320000,3,...,0.000134,-0.003256,130303700000,126.214355,20.4347,0.011281,0.098705,0.0250,LOW,XNYS
3,Consumer Goods,2022-11-18,162.0100,186.50,-0.131314,USD,156.925610,156.000000,156.000000,7,...,0.000134,-0.003256,74967580000,72.614859,18.4963,0.020463,0.098705,-1.0000,TGT,XNYS
4,Consumer Goods,2021-09-22,10.9600,54.22,-0.797861,USD,10.616040,10.432767,20.990000,31,...,0.000134,-0.003256,26153820000,25.333030,7.2262,0.006131,0.098705,0.0250,WBD,XNAS
5,Financial Services,2020-10-16,341.2700,345.00,-0.010812,USD,330.559861,325.801777,296.730000,1,...,-0.001362,0.008305,330444100000,320.073712,34.0925,0.006158,0.111755,0.0250,MA,XNYS
6,Financial Services,2020-10-16,202.3500,227.00,-0.108590,EUR,202.350000,200.850000,163.440000,4,...,-0.001362,0.008305,83304980000,83.304980,19.2200,0.015078,0.111755,0.0250,ALV,XFRA
7,Financial Services,2021-04-26,346.7700,425.00,-0.184071,USD,335.887253,334.437790,321.126000,5,...,-0.001362,0.008305,112684400000,109.148005,28.9941,0.031286,0.111755,0.0250,SPGI,XNYS
8,Financial Services,2021-09-22,51.9400,77.51,-0.329893,USD,50.309957,54.462906,54.640000,17,...,-0.001362,0.008305,44640040000,43.239093,36.7035,0.015933,0.111755,0.0250,KKR,XNYS
9,Financial Services,2022-02-23,1.5666,2.11,-0.257536,GBp,1.804631,1.809469,2.300000,416,...,-0.001362,0.008305,25085960000,28.897546,4.9264,0.013985,0.111755,-1.0000,BARC,XLON
10,Financial Services,2021-11-22,80.3600,90.28,-0.109880,GBp,92.569980,94.007319,80.650000,17,...,-0.001362,0.008305,40932640000,47.151987,49.9068,0.029316,0.111755,0.0632,LSEG,XLON
11,Real Estate,2020-11-30,639.9400,840.00,-0.238167,USD,619.856645,625.965997,588.040000,3,...,-0.001428,-0.004360,59910100000,58.029930,83.7518,0.034641,0.073808,0.0250,EQIX,XNAS
12,Real Estate,2021-11-15,39.9300,94.27,-0.576429,USD,38.676869,39.190495,66.920000,13,...,-0.001428,-0.004360,2568783000,2.488166,8.4338,0.009367,0.073808,0.0250,SLG,XNYS
13,Real Estate,2022-04-26,112.3100,190.34,-0.409951,USD,108.785355,114.316074,157.620000,7,...,-0.001428,-0.004360,105747600000,102.428904,20.8030,0.014186,0.073808,-1.0000,PLD,XNYS
14,Real Estate,2022-02-16,216.3400,288.39,-0.249835,USD,209.550562,213.388717,202.640000,4,...,-0.001428,-0.004360,100538200000,97.382991,34.3372,0.015615,0.073808,-1.0000,AMT,XNYS
15,Healthcare,2020-10-16,79.9400,130.00,-0.385077,USD,77.431228,79.057187,93.860000,5,...,-0.001242,0.043971,108060200000,104.668927,20.6715,0.007212,0.167802,0.0250,MDT,XNYS
16,Healthcare,2020-11-30,515.3100,392.00,0.314566,USD,499.137931,525.666538,282.330000,1,...,-0.001242,0.043971,495205000000,479.663890,25.2414,0.009298,0.167802,0.0250,UNH,XNYS
17,Healthcare,2021-03-05,232.9700,313.00,-0.255687,USD,225.658659,234.804869,198.600000,8,...,-0.001242,0.043971,20393950000,19.753923,12.4381,0.033630,0.167802,0.0250,LH,XNYS
18,Healthcare,2021-05-10,529.8900,553.00,-0.041790,USD,513.260364,502.878671,383.112500,3,...,-0.001242,0.043971,209918800000,203.330880,29.7824,0.028684,0.167802,0.1051,TMO,XNYS
19,Healthcare,2021-05-13,309.9000,553.00,-0.041790,USD,300.174351,300.454019,176.496600,3,...,-0.001242,0.043971,80762830000,78.228235,24.4581,0.016776,0.167802,0.0250,VRTX,XNAS
20,Healthcare,2021-10-25,739.0800,807.00,-0.084164,USD,715.885316,715.880989,496.450000,2,...,-0.001242,0.043971,80231320000,77.713406,15.5909,0.026672,0.167802,0.0250,REGN,XNAS
21,Healthcare,2022-03-08,410.4400,619.51,-0.337476,USD,397.559086,401.912674,477.320000,1,...,-0.001242,0.043971,34277110000,33.201385,52.2011,0.007406,0.167802,0.0250,IDXX,XNAS
22,Healthcare,2022-05-06,29.9600,54.53,-0.450578,USD,29.019760,29.926584,31.890000,25,...,-0.001242,0.043971,4661881000,4.515576,0.0000,0.013515,0.167802,-1.0000,TDOC,XNYS
23,Healthcare,2021-11-29,227.3000,297.44,-0.235812,USD,220.166602,214.934312,207.010000,6,...,-0.001242,0.043971,65047460000,63.006064,12.8353,0.024609,0.167802,0.0250,HCA,XNYS
24,Healthcare,2021-11-29,227.3000,297.44,-0.235812,USD,220.166602,214.934312,207.010000,6,...,-0.001242,0.043971,65047460000,63.006064,12.8353,0.024609,0.167802,-1.0000,HCA,XNYS
25,Industrials,2020-10-16,38.3900,59.10,-0.350423,EUR,38.390000,39.535000,41.450000,9,...,0.001348,0.005285,47933010000,47.933010,8.4700,0.006436,0.090203,0.0250,DPW,XFRA
26,Industrials,2020-10-16,82.1000,85.00,-0.034118,CAD,59.415255,57.379200,45.268600,9,...,0.001348,0.005285,23814770000,17.234600,18.4100,0.009961,0.090203,0.0250,MG,XTSE
27,Industrials,2021-02-23,8.9120,12.00,-0.257333,EUR,8.912000,8.806000,8.588000,100,...,0.001348,0.005285,24078260000,24.078260,5.9500,0.016602,0.090203,0.0250,EOAN,XFRA
28,Industrials,2021-06-06,104.4500,140.00,-0.253929,USD,101.172026,101.226816,121.120000,5,...,0.001348,0.005285,90074390000,87.247569,14.0436,0.009424,0.090203,0.0250,AMAT,XNAS
29,Industrials,2021-05-12,37.2200,140.00,-0.253929,EUR,37.220000,38.390000,40.692000,10,...,0.001348,0.005285,24761090000,24.761090,16.9954,0.006934,0.090203,0.0250,CRG,XDUB
30,Industrials,2021-11-29,293.3000,333.74,-0.121172,USD,284.095312,279.743045,261.780000,5,...,0.001348,0.005285,65758960000,63.695234,29.0914,0.026462,0.090203,0.0250,APD,XNYS
31,Industrials,2022-02-16,61.3200,114.42,-0.464080,USD,59.395583,56.317620,60.900000,13,...,0.001348,0.005285,4420742000,4.282005,4.6029,0.014384,0.090203,-1.0000,LPX,XNYS
32,Technology,2020-10-16,18.9520,20.00,-0.052400,EUR,18.952000,18.918000,13.975000,111,...,0.005606,-0.002401,96398220000,96.398220,12.8900,0.039189,0.186680,0.0250,DTE,XFRA
33,Technology,2020-10-16,295.2800,576.00,-0.487361,USD,286.013173,265.620170,479.800307,3,...,0.005606,-0.002401,128157000000,124.135025,27.8409,0.015984,0.186680,0.0250,NFLX,XNAS
34,Technology,2020-10-16,162.6300,120.00,0.355250,USD,157.526153,156.617079,94.040000,4,...,0.005606,-0.002401,65624480000,63.564975,28.4679,0.011738,0.186680,0.0250,ETN,XNYS
35,Technology,2020-10-16,156.7700,137.25,0.142222,USD,151.850058,152.144513,119.950000,3,...,0.005606,-0.002401,383684100000,371.642871,66.6817,0.008486,0.186680,0.0580,NVDA,XNAS
36,Technology,2021-02-23,107.0200,128.00,-0.163906,EUR,107.020000,106.000000,101.600000,4,...,0.005606,-0.002401,133840500000,133.840500,38.9500,0.007975,0.186680,0.0250,SAPA,XFRA
37,Technology,2021-09-24,39.1200,100.72,-0.611597,USD,37.892290,32.264297,50.130000,18,...,0.005606,-0.002401,2757474000000,2670.935684,19.5800,0.012706,0.186680,0.0250,TCEHY,OTCM
38,Technology,2021-09-30,98.5000,216.12,-0.544235,USD,95.408756,90.967929,137.500000,20,...,0.005606,-0.002401,1263288000000,1223.641999,19.5571,0.035547,0.186680,0.0250,GOOG,XNAS
39,Technology,2021-09-28,6.6500,13.39,-0.503361,HKD,0.823550,0.818571,0.940000,2000,...,0.005606,-0.002401,79196690000,9.807883,4.6300,0.030683,0.186680,0.0548,992,XHKG
40,Technology,2021-11-22,111.4500,439.37,-0.746341,USD,107.952344,108.066074,310.450000,5,...,0.005606,-0.002401,297106000000,287.781867,10.6318,0.010055,0.186680,0.0411,META,XNAS
41,Technology,2022-02-11,41.7600,69.80,-0.401719,USD,40.449438,40.301391,53.300000,19,...,0.005606,-0.002401,30813640000,29.846610,5.6247,0.014317,0.186680,0.0250,DELL,XNYS

In [9]:
data.to_csv("../ProcessedPortfolio.csv", index=False)

In [10]:
data

2,Sector,Buying Date,Share Price,Target Price,Deviation from\n Target Price,Currency,Current in €,Last Meeting,Initial,Shares,...,Weekly Return per Industry,Total Return per Industry,Market Cap,Market Cap in € (B),P/E ratio,Weight in Portofolio,Weight Industry,Optimization Weight (Risk Team),Ticker,Exchange
0,Consumer Goods,2020-10-16,27.5950,30.21,-0.086561,EUR,27.595000,27.750000,25.340000,40,...,0.000134,-0.003256,28856780000,28.856780,11.6653,0.020562,0.098705,0.0250,AD,XAMS
1,Consumer Goods,2021-06-06,540.4000,765.00,-0.293595,EUR,540.400000,543.600000,600.100000,4,...,0.000134,-0.003256,68774950000,68.774950,18.1789,0.040268,0.098705,0.0250,KER,XPAR
2,Consumer Goods,2022-03-08,208.4000,259.52,-0.196979,USD,201.859744,197.372488,209.320000,3,...,0.000134,-0.003256,130303700000,126.214355,20.4347,0.011281,0.098705,0.0250,LOW,XNYS
3,Consumer Goods,2022-11-18,162.0100,186.50,-0.131314,USD,156.925610,156.000000,156.000000,7,...,0.000134,-0.003256,74967580000,72.614859,18.4963,0.020463,0.098705,-1.0000,TGT,XNYS
4,Consumer Goods,2021-09-22,10.9600,54.22,-0.797861,USD,10.616040,10.432767,20.990000,31,...,0.000134,-0.003256,26153820000,25.333030,7.2262,0.006131,0.098705,0.0250,WBD,XNAS
5,Financial Services,2020-10-16,341.2700,345.00,-0.010812,USD,330.559861,325.801777,296.730000,1,...,-0.001362,0.008305,330444100000,320.073712,34.0925,0.006158,0.111755,0.0250,MA,XNYS
6,Financial Services,2020-10-16,202.3500,227.00,-0.108590,EUR,202.350000,200.850000,163.440000,4,...,-0.001362,0.008305,83304980000,83.304980,19.2200,0.015078,0.111755,0.0250,ALV,XFRA
7,Financial Services,2021-04-26,346.7700,425.00,-0.184071,USD,335.887253,334.437790,321.126000,5,...,-0.001362,0.008305,112684400000,109.148005,28.9941,0.031286,0.111755,0.0250,SPGI,XNYS
8,Financial Services,2021-09-22,51.9400,77.51,-0.329893,USD,50.309957,54.462906,54.640000,17,...,-0.001362,0.008305,44640040000,43.239093,36.7035,0.015933,0.111755,0.0250,KKR,XNYS
9,Financial Services,2022-02-23,1.5666,2.11,-0.257536,GBp,1.804631,1.809469,2.300000,416,...,-0.001362,0.008305,25085960000,28.897546,4.9264,0.013985,0.111755,-1.0000,BARC,XLON
10,Financial Services,2021-11-22,80.3600,90.28,-0.109880,GBp,92.569980,94.007319,80.650000,17,...,-0.001362,0.008305,40932640000,47.151987,49.9068,0.029316,0.111755,0.0632,LSEG,XLON
11,Real Estate,2020-11-30,639.9400,840.00,-0.238167,USD,619.856645,625.965997,588.040000,3,...,-0.001428,-0.004360,59910100000,58.029930,83.7518,0.034641,0.073808,0.0250,EQIX,XNAS
12,Real Estate,2021-11-15,39.9300,94.27,-0.576429,USD,38.676869,39.190495,66.920000,13,...,-0.001428,-0.004360,2568783000,2.488166,8.4338,0.009367,0.073808,0.0250,SLG,XNYS
13,Real Estate,2022-04-26,112.3100,190.34,-0.409951,USD,108.785355,114.316074,157.620000,7,...,-0.001428,-0.004360,105747600000,102.428904,20.8030,0.014186,0.073808,-1.0000,PLD,XNYS
14,Real Estate,2022-02-16,216.3400,288.39,-0.249835,USD,209.550562,213.388717,202.640000,4,...,-0.001428,-0.004360,100538200000,97.382991,34.3372,0.015615,0.073808,-1.0000,AMT,XNYS
15,Healthcare,2020-10-16,79.9400,130.00,-0.385077,USD,77.431228,79.057187,93.860000,5,...,-0.001242,0.043971,108060200000,104.668927,20.6715,0.007212,0.167802,0.0250,MDT,XNYS
16,Healthcare,2020-11-30,515.3100,392.00,0.314566,USD,499.137931,525.666538,282.330000,1,...,-0.001242,0.043971,495205000000,479.663890,25.2414,0.009298,0.167802,0.0250,UNH,XNYS
17,Healthcare,2021-03-05,232.9700,313.00,-0.255687,USD,225.658659,234.804869,198.600000,8,...,-0.001242,0.043971,20393950000,19.753923,12.4381,0.033630,0.167802,0.0250,LH,XNYS
18,Healthcare,2021-05-10,529.8900,553.00,-0.041790,USD,513.260364,502.878671,383.112500,3,...,-0.001242,0.043971,209918800000,203.330880,29.7824,0.028684,0.167802,0.1051,TMO,XNYS
19,Healthcare,2021-05-13,309.9000,553.00,-0.041790,USD,300.174351,300.454019,176.496600,3,...,-0.001242,0.043971,80762830000,78.228235,24.4581,0.016776,0.167802,0.0250,VRTX,XNAS
20,Healthcare,2021-10-25,739.0800,807.00,-0.084164,USD,715.885316,715.880989,496.450000,2,...,-0.001242,0.043971,80231320000,77.713406,15.5909,0.026672,0.167802,0.0250,REGN,XNAS
21,Healthcare,2022-03-08,410.4400,619.51,-0.337476,USD,397.559086,401.912674,477.320000,1,...,-0.001242,0.043971,34277110000,33.201385,52.2011,0.007406,0.167802,0.0250,IDXX,XNAS
22,Healthcare,2022-05-06,29.9600,54.53,-0.450578,USD,29.019760,29.926584,31.890000,25,...,-0.001242,0.043971,4661881000,4.515576,0.0000,0.013515,0.167802,-1.0000,TDOC,XNYS
23,Healthcare,2021-11-29,227.3000,297.44,-0.235812,USD,220.166602,214.934312,207.010000,6,...,-0.001242,0.043971,65047460000,63.006064,12.8353,0.024609,0.167802,0.0250,HCA,XNYS
24,Healthcare,2021-11-29,227.3000,297.44,-0.235812,USD,220.166602,214.934312,207.010000,6,...,-0.001242,0.043971,65047460000,63.006064,12.8353,0.024609,0.167802,-1.0000,HCA,XNYS
25,Industrials,2020-10-16,38.3900,59.10,-0.350423,EUR,38.390000,39.535000,41.450000,9,...,0.001348,0.005285,47933010000,47.933010,8.4700,0.006436,0.090203,0.0250,DPW,XFRA
26,Industrials,2020-10-16,82.1000,85.00,-0.034118,CAD,59.415255,57.379200,45.268600,9,...,0.001348,0.005285,23814770000,17.234600,18.4100,0.009961,0.090203,0.0250,MG,XTSE
27,Industrials,2021-02-23,8.9120,12.00,-0.257333,EUR,8.912000,8.806000,8.588000,100,...,0.001348,0.005285,24078260000,24.078260,5.9500,0.016602,0.090203,0.0250,EOAN,XFRA
28,Industrials,2021-06-06,104.4500,140.00,-0.253929,USD,101.172026,101.226816,121.120000,5,...,0.001348,0.005285,90074390000,87.247569,14.0436,0.009424,0.090203,0.0250,AMAT,XNAS
29,Industrials,2021-05-12,37.2200,140.00,-0.253929,EUR,37.220000,38.390000,40.692000,10,...,0.001348,0.005285,24761090000,24.761090,16.9954,0.006934,0.090203,0.0250,CRG,XDUB
30,Industrials,2021-11-29,293.3000,333.74,-0.121172,USD,284.095312,279.743045,261.780000,5,...,0.001348,0.005285,65758960000,63.695234,29.0914,0.026462,0.090203,0.0250,APD,XNYS
31,Industrials,2022-02-16,61.3200,114.42,-0.464080,USD,59.395583,56.317620,60.900000,13,...,0.001348,0.005285,4420742000,4.282005,4.6029,0.014384,0.090203,-1.0000,LPX,XNYS
32,Technology,2020-10-16,18.9520,20.00,-0.052400,EUR,18.952000,18.918000,13.975000,111,...,0.005606,-0.002401,96398220000,96.398220,12.8900,0.039189,0.186680,0.0250,DTE,XFRA
33,Technology,2020-10-16,295.2800,576.00,-0.487361,USD,286.013173,265.620170,479.800307,3,...,0.005606,-0.002401,128157000000,124.135025,27.8409,0.015984,0.186680,0.0250,NFLX,XNAS
34,Technology,2020-10-16,162.6300,120.00,0.355250,USD,157.526153,156.617079,94.040000,4,...,0.005606,-0.002401,65624480000,63.564975,28.4679,0.011738,0.186680,0.0250,ETN,XNYS
35,Technology,2020-10-16,156.7700,137.25,0.142222,USD,151.850058,152.144513,119.950000,3,...,0.005606,-0.002401,383684100000,371.642871,66.6817,0.008486,0.186680,0.0580,NVDA,XNAS
36,Technology,2021-02-23,107.0200,128.00,-0.163906,EUR,107.020000,106.000000,101.600000,4,...,0.005606,-0.002401,133840500000,133.840500,38.9500,0.007975,0.186680,0.0250,SAPA,XFRA
37,Technology,2021-09-24,39.1200,100.72,-0.611597,USD,37.892290,32.264297,50.130000,18,...,0.005606,-0.002401,2757474000000,2670.935684,19.5800,0.012706,0.186680,0.0250,TCEHY,OTCM
38,Technology,2021-09-30,98.5000,216.12,-0.544235,USD,95.408756,90.967929,137.500000,20,...,0.005606,-0.002401,1263288000000,1223.641999,19.5571,0.035547,0.186680,0.0250,GOOG,XNAS
39,Technology,2021-09-28,6.6500,13.39,-0.503361,HKD,0.823550,0.818571,0.940000,2000,...,0.005606,-0.002401,79196690000,9.807883,4.6300,0.030683,0.186680,0.0548,992,XHKG
40,Technology,2021-11-22,111.4500,439.37,-0.746341,USD,107.952344,108.066074,310.450000,5,...,0.005606,-0.002401,297106000000,287.781867,10.6318,0.010055,0.186680,0.0411,META,XNAS
41,Technology,2022-02-11,41.7600,69.80,-0.401719,USD,40.449438,40.301391,53.300000,19,...,0.005606,-0.002401,30813640000,29.846610,5.6247,0.014317,0.186680,0.0250,DELL,XNYS